apiVersion: v1
kind: Service
metadata:
  name: budgie-backend-service
spec:
  type: ClusterIP
  selector:
    app: budgie-backend
  ports:
    - protocol: TCP
      name: web
      port: 3000
      targetPort: 3000
