services:
  server:
    build: .
    env_file: .env
    image: facundoveliz/budgie-backend
    container_name: $SERVER_HOST
    ports:
      - $SERVER_PORT:$SERVER_PORT

  nginx:
    build: ./nginx
    env_file: .env
    image: facundoveliz/budgie-nginx
    container_name: $NGINX_HOST
    restart: always
    ports:
      - $NGINX_PORT:$NGINX_PORT
    depends_on:
      - server

  client:
    build: ./client
    env_file: .env
    restart: always
    container_name: $CLIENT_HOST
    image: facundoveliz/budgie-frontend
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    depends_on:
      - server
