version: "3"
services:
  server:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
      - DATABASE_URI=$DATABASE_URI
      - DATABASE_URI_TEST=$DATABASE_URI_TEST
    depends_on:
      - nginx

  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_REACT_APP_BASE_URL_PRODUCTION=$NEXT_PUBLIC_REACT_APP_BASE_URL_PRODUCTION
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - DOMAIN=$DOMAIN
      - VPS_ADRESS=$VPS_ADRESS
    command: [nginx, '-g', 'daemon off;']
