name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Node.js
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0

      - name: Run unit tests
        uses: oven-sh/setup-bun@v2
      - run: bun run test
        env: # just for local testing purpouses
          JWT_PRIVATE_KEY: password
          DATABASE_URI_TEST: mongodb://localhost:27017/budgie

      - name: Build NextJS
        uses: oven-sh/setup-bun@v2
      - run: cd client
      - run: bun install
      - run: bun run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: |
          docker build -t facundoveliz/budgie .
          docker push facundoveliz/budgie
