name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Node.js
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build

      - name: Login to DockerHub registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tag_with_sha: true
          tags: ${{ github.sha }}
