name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Node.js
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tag_with_sha: true
          tags: ${{ github.sha }}
